services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "WubbaLubbaDubDub@RichSanchez6"
    volumes:
      - sql-data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P WubbaLubbaDubDub@RichSanchez6 -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sql-data:
